hc <- read.csv("household_power_consumption.txt", sep = ";")
hc = transform(hc, Date = as.Date(Date, format = "%d/%m/%Y"))
startDate = as.Date("2007-02-01")
endDate = as.Date("2007-02-02")
hc = subset(hc, Date >= startDate & Date <= endDate)
png("plot2.png", 480, 480) 
hc$Global_active_power = as.numeric(as.character(hc$Global_active_power))
hc$fullDate <- paste(as.character(hc$Date), as.character(hc$Time))
hc$fullDate <- as.POSIXct(hc$fullDate, format = "%Y-%m-%d %H:%M:%S")
plot(hc$fullDate, hc$Global_active_power, type = "l", xlab = "", ylab = "Global Active Power(kilowatts)")
dev.off()