hc <- read.csv("household_power_consumption.txt", sep = ";")
hc = transform(hc, Date = as.Date(Date, format = "%d/%m/%Y"))
startDate = as.Date("2007-02-01")
endDate = as.Date("2007-02-02")
hc = subset(hc, Date >= startDate & Date <= endDate)
png("plot3.png", 480, 480) 
hc$fullDate <- paste(as.character(hc$Date), as.character(hc$Time))
hc$fullDate <- as.POSIXct(hc$fullDate, format = "%Y-%m-%d %H:%M:%S")
with(hc, plot(hc$fullDate, as.numeric(as.character(hc$Sub_metering_1)), type = "l", xlab = "", ylab = "Energy sub metering"))
lines(hc$fullDate, as.numeric(as.character(hc$Sub_metering_2)), col = "red")
lines(hc$fullDate, as.numeric(as.character(hc$Sub_metering_3)), col = "blue")
legend("topright", col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), lty = 1)
dev.off()